"deadlift1226 vim config

execute pathogen#infect()
syntax on
filetype plugin indent on
filetype plugin on

set omnifunc=syntaxcomplete
set runtimepath+=~/.vim
"
set number
set mouse+=a
"
"searching 
set ignorecase
set smartcase
set incsearch
set autowrite
set hidden
let g:ycm_path_to_python_interpreter = '~/miniconda3/bin/python'
"
"MacBook Touchbar
inoremap fj <ESC>
cnoremap fj <ESC>
"Search and Replace
nmap sr <ESC>:%s///gc
"
"Delete all below current line
nmap db <ESC>:+,$d
"
" set buffers to leave off where left
nnoremap <Space> za
vnoremap <Space> za
"
"""""Refocus fold
nnoremap ,z zMzvzz
""""unfold top regardless of cursor location
nnoremap Z zCzO
"
" folding
set foldmethod=indent
set foldnestmax=10
set foldlevel=0
set nofoldenable
"
"buffers to save cursor location
au BufWinLeave * mkview
au BufWinEnter * silent loadview
"
"security, remember :X to encrypt, to remove passwd :X and leave blank
setlocal cm=blowfish2 
"
"fix backspace errors
set backspace=indent,eol,start
"
set wildmenu
set wildmode=list:longest,full
"
"proper tab
set smarttab
set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab
"proper indent
set ai
set si
set wrap
"no swapfile or backup, be careful ;)
set noswapfile
set nobackup
set nowritebackup
"
" no annoying bell
set noerrorbells
set novisualbell
set tm=500
"
" typos
command! Q q
command! W w
command! WQ wq
command! Wq wq
"
"Plug-ins
let g:rainbow_active = 1 "0 if you want to enable it later via :RainbowToggle 
set updatetime=500
"colors
set t_Co=256

"git init
"git submodule add git://github.com/mephux/bro.vim.git ./bundle/bro
"git submodule add git://github.com/luochen1990/rainbow ./bundle/rainbow
"git submodule add git://github.com/flazz/vim-colorschemes ./bundle/vim-colorschemes
"git submodule add git://github.com/ervandew/supertab ./bundle/supertab
