# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="bolverk"
DISABLE_UPDATE_PROMPT="true"
ZSH_DISABLE_COMPFIX=true
export UPDATE_ZSH_DAYS=13
plugins=(git)
source $ZSH/oh-my-zsh.sh
source /Users/damorgan/.zsh/aliases
source /Users/damorgan/.zsh/funcs
source /Users/damorgan/.zsh/zshenv
unsetopt beep
unsetopt list_beep
unsetopt hist_beep
HISTFILE=~/.zsh_history
HISTSIZE=2048
SAVEHIST=2048
setopt append_history       # append history
setopt hist_reduce_blanks   # removes un-needed blank spaces and lines from history
setopt hist_verify          # verify before executing history command
setopt extended_history     # save time/date in zsh_history
setopt share_history        # share history between sessions
# alerts 
watch=all                   # watch all logins
logcheck=15                 # every 15 seconds

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

